[aws]
app_machine ansible_host=3.239.23.15 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/terraform-key

[azure]
azure_vm ansible_host=172.191.94.139 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/terraform-key

